2025-05-07 19:37:48,242 INFO: Connection established with ('192.168.94.135', 49697)
2025-05-07 19:41:02,746 INFO: Connection established with ('192.168.94.135', 49698)
2025-05-07 19:45:56,722 INFO: Connection established with ('192.168.94.135', 49714)
2025-05-07 19:48:16,140 INFO: Connection established with ('192.168.94.135', 49722)
2025-05-07 19:51:43,389 INFO: Connection established with ('192.168.94.135', 49735)
2025-05-07 19:57:47,679 INFO: Connection established with ('192.168.94.135', 49764)
2025-05-07 20:02:24,000 INFO: Connection established with ('192.168.94.135', 49765)
2025-05-07 20:06:39,923 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:09:37,047 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:09:41,010 ERROR: Server encountered an error
Traceback (most recent call last):
  File "/mnt/hgfs/Scripting/Homework 3/server.py", line 141, in main
    repl(conn)
  File "/mnt/hgfs/Scripting/Homework 3/server.py", line 97, in repl
    send_json(conn, {"command": "exit"})
  File "/mnt/hgfs/Scripting/Homework 3/server.py", line 25, in send_json
    conn.sendall(header + data)
ConnectionResetError: [Errno 104] Connection reset by peer
2025-05-07 20:10:09,096 INFO: Connection established with ('192.168.94.135', 49675)
2025-05-07 20:14:22,957 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:19:31,976 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:20:44,021 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:26:55,662 INFO: Connection established with ('192.168.94.135', 49674)
2025-05-07 20:35:54,374 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:37:16,986 INFO: Connection established with ('192.168.94.135', 49676)
2025-05-07 20:39:31,526 INFO: Connection established with ('192.168.94.135', 49673)
2025-05-07 20:46:14,618 INFO: Connection established with ('192.168.94.135', 49677)
2025-05-07 20:47:34,154 INFO: Connection established with ('192.168.94.135', 49678)
